/** @type {import('tailwindcss').Config} */

module.exports = {
  content: [
    "./src/**/*.{html,jsx, ts,tsx}",
    "./public/index.html",
    "./src/pages/Login.jsx",
    "./src/pages/ViewEstados.jsx",
    "./src/pages/MyExercise.jsx",
    "./src/pages/ViewActivity.jsx",
    "./src/pages/SignUp.jsx",
    "./src/components/Modal.jsx",
    "./src/components/Sidebar.jsx",
    "./src/pages/Alimentos.jsx",
    "./src/pages/GlucoseRegister.jsx",
    "./src/pages/AllGlucoseRegister.jsx",
    "./src/pages/DailyRecord.jsx",
    "./src/pages/Exercise.jsx",
    "./src/pages/InsulineRegister.jsx",
    "./src/pages/WaterRegister.jsx",
    "./src/pages/Files.jsx",
    "./src/pages/AllFiles.jsx",
    "./src/pages/MyDates.jsx",
    "./src/pages/Citas.jsx",
    "./src/pages/Estados.jsx",
    "./src/pages/Activities.jsx",
    "./src/pages/AllAlimentosRegister.jsx",
    "./src/pages/AtipicDayRegister.jsx",
    "./src/pages/AlimentosRegister.jsx",
    "./src/pages/AllActivitiesRegister.jsx",
    "./src/pages/AllAtipicDayRegister.jsx",
    "./src/pages/AllCitas.jsx",
    "./src/pages/AllDailyRecord.jsx",
    "./src/pages/Main.jsx",
    "./src/pages/Index.jsx",
    "./src/components/NavRegistro.jsx",
    "./src/components/Paginacion.jsx",
    "./src/components/Modal.jsx",
    "./src/components/ModalGlucosa.jsx",
    "./src/pages/Profile.jsx",
    "./src/pages/SleepHours.jsx",
    "./src/pages/MyGlucoseRegister.jsx",
    "./node_modules/flowbite-react/lib/esm/**/*.js",
  ],
  theme: {
    extend: {
      fontFamily: {
        fuentesec: ["Dancing Script", "cursive"],
        fuenteTechani: ["Open Sans", "sans-serif"],
      },
      colors: {
        azul: "#277BC0",
        azulSecundario: "#4DBDEB",
        amarillo: "#FFE08C",
        fondoGris: "#F6F6F6",
        azulFondo: "#18578B",
        azulHover: "#2B8EDE",
        fondo: "#ECECEC",
      },
    },
  },
  plugins: [require("flowbite/plugin")],
};
